from . import crm_team
from . import project_issue
from . import project_project
from . import project_task
from . import project_workspace
from . import project_version
from . import project_sprint
from . import project_task_sprint_history
from . import project_phase
from . import ir_ui_menu
from . import res_users