from . import crm_team
from . import crm_brick
from . import crm_territory
from . import crm_team_member
from . import crm_segment
from . import crm_segmentation
from . import crm_medical_specialization
from . import crm_promotion_dist_plan
from . import crm_unit_type
from . import crm_unit_code
from . import crm_unit
from . import crm_partner
from . import crm_selection_period
from . import crm_selection
from . import crm_visit