{
    'name': 'Agile Project Management',
    'version': '17.0.1.0',
    'sequence': -200,
    'category': 'Productivity',
    'license': 'LGPL-3',
    'author': 'Atila Kardan',
    'maintainer': 'Kardan.DX',
    'summary': 'Agile Project Management',
    'description': """
    Agile features for Project Management
    """,
    'depends': [
        'project', 
        'hr',
        'crm',
        'mail',
        'base_automation',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/project_security.xml',
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        'data/base_automation_data.xml',
        'report/project_project_template.xml',
        'report/project_task_template.xml',
        'report/ir_action_report.xml',
        'views/crm_team_views.xml',
        'views/project_project_views.xml',
        'views/project_milestone_views.xml',
        'views/project_issue_views.xml',        
        'views/project_task_views.xml',
        'views/project_team_views.xml',
        'views/project_workspace_views.xml',
        'views/project_board_views.xml',        
        'views/project_sprint_views.xml',       
        'views/project_version_views.xml',
        'views/project_phase_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ak_project/static/src/components/**/*',
            # 'ak_project/static/src/js/selection_issue_type.js',
            'ak_project/static/src/css/selection_issue_type.css',
            'ak_project/static/src/xml/**/*',
            'ak_project/static/src/js/web_tree_duplicate.esm.js',
            'ak_project/static/src/js/task_list.js',
            'ak_project/static/src/xml/task_list.xml',
        ],
    },    
    'installable': True,
    'application': True,
}
