# -*- coding: utf-8 -*-
{
    'name': 'CRM Pharma',
    'version': '18.0.1.0',
    'author': 'Atila Kardan',
    'category': 'Sales/CRM',
    'summary': 'CRM Management',
    'sequence': -90,
    'description': """
CRM Pharma
====================
CRM for a Pharmaceutical Company
    """,
    'website': 'https:/kardan.digital/app/crm',
    'images': [],
    'depends': [
        'base',
        # 'web',
        'crm',
        'sales_team',
        'contacts',
    ],
    'data': [
        'security/crm_security.xml',
        'security/ir.model.access.csv',
        'wizards/crm_promotion_dist_plan_wizard_view.xml',
        'views/crm_team_views.xml',
        'views/crm_team_member_views.xml',
        'views/crm_brick_views.xml',
        'views/crm_territory_views.xml',
        'views/crm_segment.xml',
        'views/crm_visit.xml',
        'views/crm_menu.xml',
        'views/crm_segmentation.xml',
        'views/crm_medical_specialization.xml',
        'views/crm_unit_type_views.xml',
        'views/crm_unit_code_views.xml',
        'views/crm_unit_views.xml',
        'views/crm_partner_views.xml',
        'views/crm_promotion_dist_plan_views.xml',
        'views/crm_selection_period_views.xml',
        'views/crm_selection_views.xml',
        'data/crm_medical_specialization_data.xml',
        'data/crm_unit_type_data.xml',
        'data/crm_unit_code_data.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
