# -*- coding: utf-8 -*-
{
    'name': 'CRM Pharma',
    'version': '15.0.1.0',
    'author': 'Atila Kardan',
    'category': 'Sales/CRM',
    'summary': 'CRM Management',
    'sequence': -90,
    'description': """
CRM Pharma
====================
CRM for a Pharmaceutical Company
    """,
    'website': 'https://www.akka.com/app/crm',
    'images': [],
    'depends': [
        'base',
        'web',
        'crm',
        'sales_team',
        'contacts',
    ],
    'data': [
        'security/crm_security.xml',
        'security/ir.model.access.csv',
        'wizards/crm_promotion_dist_plan_wizard_view.xml',
        'views/crm_team_views.xml',
        'views/crm_team_member_views.xml',
        'views/crm_brick_views.xml',
        'views/crm_territory_views.xml',
        'views/crm_segment.xml',
        'views/crm_visit.xml',
        'views/crm_menu.xml',
        'views/crm_segmentation.xml',
        'views/crm_medical_specialization.xml',
        'views/crm_unit_type_views.xml',
        'views/crm_unit_code_views.xml',
        'views/crm_unit_views.xml',
        'views/crm_partner_views.xml',
        'views/crm_promotion_dist_plan_views.xml',
        'views/crm_selection_period_views.xml',
        'views/crm_selection_views.xml',
        'data/crm_medical_specialization_data.xml',
        'data/crm_unit_type_data.xml',
        'data/crm_unit_code_data.xml',
    ],
    'qweb': [
        # 'static/src/xml/tree_widget_template.xml',
    ],
    'demo': [],
    'assets': {
        'web.assets_backend': [
            'ak_crm/views/tree_widget.xml',
            # 'ak_crm/static/src/**/*',
            # 'ak_crm/static/src/js/*.js',
            # 'ak_crm/static/src/css/style.min.css',
            # 'ak_crm/static/src/xml/*.xml',
        ],
        'web.assets_frontend': [],
        'web.assets_tests': [],
        'web.qunit_suite_tests': [],
        'web.assets_qweb': [],
        'hr.department': (),
    },
    # 'icon': "static/icon.png",
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
